
export const GET_PUBLICATION_SUCCESS = "GET_PUBLICATION_SUCCESS"
export const GET_PUBLICATION_FAILURE = "GET_PUBLICATION_FAILURE"
export const GET_PUBLICATION_REQUEST = "GET_PUBLICATION_REQUEST"

export const GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS"
export const GET_PUBLICATIONS_FAILURE = "GET_PUBLICATIONS_FAILURE"
export const GET_PUBLICATIONS_REQUEST = "GET_PUBLICATIONS_REQUEST"
