
export const GET_PUBLICATION = 'GET_PUBLICATION'
export const GET_PUBLICATION_SUCCESS = 'GET_PUBLICATION_SUCCESS'
export const GET_PUBLICATION_FAILURE = 'GET_PUBLICATION_FAILURE'
export const GET_PUBLICATION_ATTEMPT = 'GET_PUBLICATION_ATTEMPT'
