export const GET_PUBLICATION_SUCCESS = "GET_PUBLICATION_SUCCESS"
export const GET_PUBLICATION_FAILURE = "GET_PUBLICATION_FAILURE"
export const GET_PUBLICATION_REQUEST = "GET_PUBLICATION_REQUEST"

export const GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS"
export const GET_PUBLICATIONS_FAILURE = "GET_PUBLICATIONS_FAILURE"
export const GET_PUBLICATIONS_REQUEST = "GET_PUBLICATIONS_REQUEST"

export const GET_ISSUES_REQUEST = "GET_ISSUES_REQUEST"
export const GET_ISSUES_FAILURE = "GET_ISSUES_FAILURE"
export const GET_ISSUES_SUCCESS = "GET_ISSUES_SUCCESS"

export const GET_ISSUE_REQUEST = "GET_ISSUE_REQUEST"
export const GET_ISSUE_FAILURE = "GET_ISSUE_FAILURE"
export const GET_ISSUE_SUCCESS = "GET_ISSUE_SUCCESS"

export const NEW_ISSUE_REQUEST = "NEW_ISSUE_REQUEST"
export const NEW_ISSUE_FAILURE = "NEW_ISSUE_FAILURE"
export const NEW_ISSUE_SUCCESS = "NEW_ISSUE_SUCCESS"

export const UPDATE_ISSUE_REQUEST = "UPDATE_ISSUE_REQUEST"
export const UPDATE_ISSUE_FAILURE = "UPDATE_ISSUE_FAILURE"
export const UPDATE_ISSUE_SUCCESS = "UPDATE_ISSUE_SUCCESS"

export const UPLOAD_ISSUE_REQUEST = "UPLOAD_ISSUE_REQUEST"
export const UPLOAD_ISSUE_FAILURE = "UPLOAD_ISSUE_FAILURE"
export const UPLOAD_ISSUE_SUCCESS = "UPLOAD_ISSUE_SUCCESS"

export const PROCESS_ISSUE_REQUEST = "PROCESS_ISSUE_REQUEST"
export const PROCESS_ISSUE_FAILURE = "PROCESS_ISSUE_FAILURE"
export const PROCESS_ISSUE_SUCCESS = "PROCESS_ISSUE_SUCCESS"
